version: "3.9"

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgres:postgres@iac-postgres.cybbkocdthrb.eu-central-1.rds.amazonaws.com:5432/postgres
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask_app
    ports:
      - "80:80"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
networks:
  localprom:
    driver: bridge