global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "monitoring"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["prometheus:9090"]

  - job_name: "application"
    scrape_interval: 5s
    static_configs:
    - targets: ["flask_app:5000"]